package com.sami.winetasting;

import android.app.*;
import android.content.*;
import android.graphics.Color;
import android.graphics.pdf.PdfDocument;
import android.net.Uri;
import android.os.Bundle;
import android.view.*;
import android.widget.*;
import java.io.File;
import java.io.FileOutputStream;
import java.text.SimpleDateFormat;
import java.util.*;

public class TastingActivity extends Activity {
    LinearLayout root; Tasting t; Map<String,EditText> edits=new HashMap<>(); Map<String,RadioGroup> radios=new HashMap<>(); List<CheckBox> aromaChecks=new ArrayList<>(); List<CheckBox> whyChecks=new ArrayList<>();
    int wine=Color.rgb(122,23,50), nose=Color.rgb(47,107,70), palate=Color.rgb(154,77,43), concl=Color.rgb(39,76,119), ink=Color.rgb(31,37,48), muted=Color.rgb(105,105,105);
    int dp(float x){ return (int)(x*getResources().getDisplayMetrics().density+0.5f); }
    TextView tv(String s,int sp,boolean bold){ TextView v=new TextView(this); v.setText(s); v.setTextSize(sp); v.setTextColor(ink); if(bold)v.setTypeface(null,1); return v; }
    @Override public void onCreate(Bundle b){ super.onCreate(b); long id=getIntent().getLongExtra("id",-1); t=id==-1?new Tasting():TastingStore.find(this,id); if(t==null)t=new Tasting(); build(); populate(); }
    void build(){
        ScrollView sc=new ScrollView(this); sc.setBackgroundColor(Color.rgb(255,253,249)); root=new LinearLayout(this); root.setOrientation(LinearLayout.VERTICAL); root.setPadding(dp(14),dp(16),dp(14),dp(40)); sc.addView(root);
        LinearLayout top=new LinearLayout(this); top.setGravity(Gravity.CENTER_VERTICAL); Button back=new Button(this); back.setText("‹"); back.setTextSize(28); back.setBackgroundColor(Color.TRANSPARENT); top.addView(back,new LinearLayout.LayoutParams(dp(54),dp(54))); back.setOnClickListener(v->finish());
        LinearLayout head=new LinearLayout(this); head.setOrientation(LinearLayout.VERTICAL); head.addView(tv("WINE TASTING NOTES",25,true)); TextView st=tv("LOOK  ·  SMELL  ·  TASTE  ·  CONCLUDE",11,true); st.setTextColor(wine); head.addView(st); top.addView(head,new LinearLayout.LayoutParams(0,-2,1)); root.addView(top);
        cardStart("WINE DETAILS",wine); field("wine","Wine"); field("producer","Producer"); rowFields(new String[]{"vintage","grape"},new String[]{"Vintage","Grape variety"}); field("region","Region / Country"); rowFields(new String[]{"date","temperature"},new String[]{"Date","Serving temp °C"}); field("notes","Notes"); cardEnd();
        section("1. APPEARANCE", "Clarity · Intensity · Colour", wine); radio("clarity","Clarity",new String[]{"Clear","Hazy"}); radio("appearanceIntensity","Intensity",new String[]{"Pale","Medium","Deep"}); radio("color","Colour",new String[]{"Lemon green","Lemon","Gold","Amber","Brown","Pink","Pink-orange","Orange","Purple","Ruby","Garnet","Tawny","Brown"}); field("appearanceNotes","Appearance notes");
        section("2. NOSE", "Condition · Intensity · Primary · Secondary · Tertiary", nose); radio("noseCondition","Condition",new String[]{"Clean","Unclean / Faulty"}); radio("noseIntensity","Intensity",new String[]{"Light","Medium","Pronounced"}); aromaGroup("PRIMARY AROMAS & FLAVOURS", new String[]{"Blossom","Rose","Violet","Apple","Pear","Gooseberry","Grape","Grapefruit","Lemon","Lime","Orange","Peach","Apricot","Nectarine","Banana","Lychee","Mango","Melon","Passion fruit","Pineapple","Redcurrant","Cranberry","Raspberry","Strawberry","Red cherry","Red plum","Blackcurrant","Blackberry","Blueberry","Black cherry","Black plum","Green bell pepper","Grass","Tomato leaf","Asparagus","Eucalyptus","Mint","Fennel","Dill","Dried herbs","Black pepper","White pepper","Liquorice","Unripe fruit","Ripe fruit","Dried fruit","Cooked fruit","Wet stones","Candy"});
        aromaGroup("SECONDARY AROMAS & FLAVOURS", new String[]{"Biscuit","Pastry","Bread","Toasted bread","Bread dough","Cheese","Yogurt","Butter","Cream","Vanilla","Cloves","Coconut","Cedar","Charred wood","Smoke","Chocolate","Coffee"});
        aromaGroup("TERTIARY AROMAS & FLAVOURS", new String[]{"Dried fruit","Leather","Earth","Mushroom","Meat","Tobacco","Wet leaves","Forest floor","Caramel","Orange marmalade","Petrol (gasoline)","Cinnamon","Ginger","Nutmeg","Almond","Hazelnut","Honey","Walnut"});
        field("mainAromas","Main aromas I perceive (3–5)"); field("noseNotes","Additional nose notes");
        section("3. PALATE", "Sweetness · Acidity · Tannin · Alcohol · Body · Flavour · Finish", palate); radio("sweetness","Sweetness",new String[]{"Dry","Off-dry","Medium","Sweet"}); radio("acidity","Acidity",new String[]{"Low","Medium","High"}); radio("tannin","Tannin (red wines)",new String[]{"Low","Medium","High"}); radio("alcohol","Alcohol",new String[]{"Low","Medium","High"}); radio("body","Body",new String[]{"Light","Medium","Full"}); radio("flavourIntensity","Flavour intensity",new String[]{"Light","Medium","Pronounced"}); radio("finish","Finish",new String[]{"Short","Medium","Long"}); field("primaryFlavours","Primary flavours"); field("secondaryFlavours","Secondary flavours"); field("tertiaryFlavours","Tertiary flavours");
        section("4. CONCLUSIONS", "Quality · Why? · Overall impression", concl); radio("quality","Quality",new String[]{"Faulty","Poor","Acceptable","Good","Very Good","Outstanding"}); whyGroup(); field("overall","Overall tasting note"); rowFields(new String[]{"score"},new String[]{"Personal score / 100"}); radio("buyAgain","Would I buy it again?",new String[]{"Yes","Maybe","No"});
        Button save=new Button(this); save.setText("SAVE TASTING"); save.setTextColor(Color.WHITE); save.setTextSize(16); save.setTypeface(null,1); save.setBackgroundResource(R.drawable.btn_wine); save.setAllCaps(false); LinearLayout.LayoutParams sp=new LinearLayout.LayoutParams(-1,dp(58)); sp.setMargins(0,dp(22),0,dp(10)); root.addView(save,sp); save.setOnClickListener(v->save(false));
        Button pdf=new Button(this); pdf.setText("EXPORT SUMMARY PDF"); pdf.setAllCaps(false); root.addView(pdf,new LinearLayout.LayoutParams(-1,dp(52))); pdf.setOnClickListener(v->{save(true); exportPdf();});
        setContentView(sc);
    }
    void cardStart(String title,int c){ TextView h=tv(title,16,true); h.setTextColor(c); h.setPadding(0,dp(14),0,dp(7)); root.addView(h); }
    void cardEnd(){}
    void section(String title,String sub,int c){ TextView h=tv(title,20,true); h.setTextColor(Color.WHITE); h.setBackgroundColor(c); h.setPadding(dp(12),dp(10),dp(12),dp(10)); LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2); p.setMargins(0,dp(18),0,0); root.addView(h,p); TextView s=tv(sub,12,false); s.setTextColor(c); s.setPadding(dp(4),dp(6),0,dp(6)); root.addView(s); }
    void field(String key,String label){ TextView l=tv(label,13,true); l.setPadding(0,dp(8),0,dp(4)); root.addView(l); EditText e=new EditText(this); e.setTextSize(15); e.setSingleLine(false); e.setMinLines(key.toLowerCase().contains("note")||key.contains("Flavours")||key.equals("mainAromas")?2:1); e.setBackgroundResource(R.drawable.input_bg); e.setPadding(dp(10),dp(8),dp(10),dp(8)); root.addView(e,new LinearLayout.LayoutParams(-1,-2)); edits.put(key,e); }
    void rowFields(String[] keys,String[] labels){ LinearLayout row=new LinearLayout(this); row.setOrientation(LinearLayout.HORIZONTAL); for(int i=0;i<keys.length;i++){ LinearLayout col=new LinearLayout(this); col.setOrientation(LinearLayout.VERTICAL); TextView l=tv(labels[i],13,true); l.setPadding(0,dp(8),0,dp(4)); col.addView(l); EditText e=new EditText(this); e.setTextSize(15); e.setSingleLine(true); e.setBackgroundResource(R.drawable.input_bg); e.setPadding(dp(10),dp(8),dp(10),dp(8)); col.addView(e,new LinearLayout.LayoutParams(-1,-2)); edits.put(keys[i],e); LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(0,-2,1); if(i>0)cp.setMargins(dp(8),0,0,0); row.addView(col,cp);} root.addView(row); }
    void radio(String key,String label,String[] options){ TextView l=tv(label,14,true); l.setPadding(0,dp(8),0,dp(2)); root.addView(l); RadioGroup g=new RadioGroup(this); g.setOrientation(RadioGroup.HORIZONTAL); g.setPadding(0,0,0,dp(4)); for(String o:options){ RadioButton r=new RadioButton(this); r.setText(o); r.setTextSize(13); r.setPadding(0,0,dp(10),0); g.addView(r,new RadioGroup.LayoutParams(-2,-2)); } root.addView(g); radios.put(key,g); }
    void aromaGroup(String title,String[] items){ TextView h=tv(title,13,true); h.setTextColor(nose); h.setPadding(0,dp(10),0,dp(3)); root.addView(h); LinearLayout wrap=new LinearLayout(this); wrap.setOrientation(LinearLayout.VERTICAL); for(int i=0;i<items.length;i+=2){ LinearLayout row=new LinearLayout(this); for(int j=i;j<Math.min(i+2,items.length);j++){ CheckBox c=new CheckBox(this); c.setText(items[j]); c.setTextSize(13); aromaChecks.add(c); row.addView(c,new LinearLayout.LayoutParams(0,-2,1)); } wrap.addView(row);} root.addView(wrap); }
    void whyGroup(){ TextView h=tv("Why?",14,true); root.addView(h); String[] x={"Balanced","Good intensity","Complexity","Long finish","Fruit concentration","Oak well integrated","Acidity balanced","Tannins balanced"}; for(int i=0;i<x.length;i+=2){ LinearLayout row=new LinearLayout(this); for(int j=i;j<Math.min(i+2,x.length);j++){ CheckBox c=new CheckBox(this); c.setText(x[j]); c.setTextSize(13); whyChecks.add(c); row.addView(c,new LinearLayout.LayoutParams(0,-2,1)); } root.addView(row);} }
    String selected(RadioGroup g){ int id=g.getCheckedRadioButtonId(); if(id==-1)return ""; return ((RadioButton)g.findViewById(id)).getText().toString(); }
    void setRadio(String key,String value){ RadioGroup g=radios.get(key); if(g==null||value==null)return; for(int i=0;i<g.getChildCount();i++){ RadioButton r=(RadioButton)g.getChildAt(i); if(value.equals(r.getText().toString())){r.setChecked(true);break;} } }
    void populate(){
        setEdit("wine",t.wine);setEdit("producer",t.producer);setEdit("vintage",t.vintage);setEdit("grape",t.grape);setEdit("region",t.region);setEdit("date",t.date);setEdit("temperature",t.temperature);setEdit("notes",t.notes);setEdit("appearanceNotes",t.appearanceNotes);setEdit("mainAromas",t.mainAromas);setEdit("noseNotes",t.noseNotes);setEdit("primaryFlavours",t.primaryFlavours);setEdit("secondaryFlavours",t.secondaryFlavours);setEdit("tertiaryFlavours",t.tertiaryFlavours);setEdit("overall",t.overall);setEdit("score",t.score);
        setRadio("clarity",t.clarity);setRadio("appearanceIntensity",t.appearanceIntensity);setRadio("color",t.color);setRadio("noseCondition",t.noseCondition);setRadio("noseIntensity",t.noseIntensity);setRadio("sweetness",t.sweetness);setRadio("acidity",t.acidity);setRadio("tannin",t.tannin);setRadio("alcohol",t.alcohol);setRadio("body",t.body);setRadio("flavourIntensity",t.flavourIntensity);setRadio("finish",t.finish);setRadio("quality",t.quality);setRadio("buyAgain",t.buyAgain);
        for(CheckBox c:aromaChecks) if(t.aromas.contains(c.getText().toString())) c.setChecked(true); if(t.why!=null) for(CheckBox c:whyChecks) if(Arrays.asList(t.why.split("\\|",-1)).contains(c.getText().toString())) c.setChecked(true);
        if(t.date.isEmpty()) setEdit("date",new SimpleDateFormat("yyyy-MM-dd",Locale.US).format(new Date()));
    }
    void setEdit(String k,String v){ if(edits.get(k)!=null)edits.get(k).setText(v==null?"":v); }
    String e(String k){ return edits.get(k)==null?"":edits.get(k).getText().toString().trim(); }
    void save(boolean quiet){
        t.wine=e("wine");t.producer=e("producer");t.vintage=e("vintage");t.grape=e("grape");t.region=e("region");t.date=e("date");t.temperature=e("temperature");t.notes=e("notes");t.appearanceNotes=e("appearanceNotes");t.mainAromas=e("mainAromas");t.noseNotes=e("noseNotes");t.primaryFlavours=e("primaryFlavours");t.secondaryFlavours=e("secondaryFlavours");t.tertiaryFlavours=e("tertiaryFlavours");t.overall=e("overall");t.score=e("score");
        t.clarity=selected(radios.get("clarity"));t.appearanceIntensity=selected(radios.get("appearanceIntensity"));t.color=selected(radios.get("color"));t.noseCondition=selected(radios.get("noseCondition"));t.noseIntensity=selected(radios.get("noseIntensity"));t.sweetness=selected(radios.get("sweetness"));t.acidity=selected(radios.get("acidity"));t.tannin=selected(radios.get("tannin"));t.alcohol=selected(radios.get("alcohol"));t.body=selected(radios.get("body"));t.flavourIntensity=selected(radios.get("flavourIntensity"));t.finish=selected(radios.get("finish"));t.quality=selected(radios.get("quality"));t.buyAgain=selected(radios.get("buyAgain"));
        t.aromas.clear(); for(CheckBox c:aromaChecks)if(c.isChecked())t.aromas.add(c.getText().toString()); StringBuilder w=new StringBuilder();for(CheckBox c:whyChecks)if(c.isChecked()){if(w.length()>0)w.append("|");w.append(c.getText());}t.why=w.toString(); TastingStore.save(this,t); if(!quiet)Toast.makeText(this,"Tasting saved",Toast.LENGTH_SHORT).show();
    }
    void exportPdf(){
        try{
            PdfDocument doc=new PdfDocument(); PdfDocument.PageInfo pi=new PdfDocument.PageInfo.Builder(595,842,1).create(); PdfDocument.Page p=doc.startPage(pi); android.graphics.Canvas c=p.getCanvas(); android.graphics.Paint paint=new android.graphics.Paint(1); paint.setColor(ink); paint.setTextSize(22); paint.setFakeBoldText(true); c.drawText("WINE TASTING NOTES",40,55,paint); paint.setFakeBoldText(false); paint.setTextSize(11); int y=88; String[] lines={"Wine: "+t.wine,"Producer: "+t.producer,"Vintage: "+t.vintage+"    Grape: "+t.grape,"Region / Country: "+t.region,"Date: "+t.date+"    Serving temp: "+t.temperature,"","APPEARANCE","Clarity: "+t.clarity+"    Intensity: "+t.appearanceIntensity+"    Colour: "+t.color,t.appearanceNotes,"","NOSE","Condition: "+t.noseCondition+"    Intensity: "+t.noseIntensity,"Aromas: "+String.join(", ",t.aromas),"Main aromas: "+t.mainAromas,t.noseNotes,"","PALATE","Sweetness: "+t.sweetness+"    Acidity: "+t.acidity+"    Tannin: "+t.tannin,"Alcohol: "+t.alcohol+"    Body: "+t.body+"    Flavour intensity: "+t.flavourIntensity+"    Finish: "+t.finish,"Primary: "+t.primaryFlavours,"Secondary: "+t.secondaryFlavours,"Tertiary: "+t.tertiaryFlavours,"","CONCLUSIONS","Quality: "+t.quality+"    Score: "+t.score+"/100    Buy again: "+t.buyAgain,"Why: "+t.why.replace('|', ','),"Overall: "+t.overall}; for(String line:lines){ for(String s:wrap(line,88)){ c.drawText(s,40,y,paint); y+=16;} y+=3; if(y>810)break;} doc.finishPage(p); File dir=new File(getExternalFilesDir(null),"exports");dir.mkdirs(); File f=new File(dir,(t.wine.isEmpty()?"tasting":t.wine.replaceAll("[^a-zA-Z0-9_-]","_"))+".pdf"); FileOutputStream out=new FileOutputStream(f);doc.writeTo(out);out.close();doc.close(); new AlertDialog.Builder(this).setTitle("PDF exported").setMessage(f.getAbsolutePath()).setPositiveButton("OK",null).show();
        }catch(Exception ex){Toast.makeText(this,"PDF export failed",Toast.LENGTH_LONG).show();}
    }
    List<String> wrap(String s,int max){ List<String> o=new ArrayList<>(); if(s==null||s.isEmpty()){o.add("");return o;} while(s.length()>max){int cut=s.lastIndexOf(' ',max);if(cut<1)cut=max;o.add(s.substring(0,cut));s=s.substring(cut).trim();}o.add(s);return o; }
}
